# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86e2e1e155e39a838a0249eafdf58b55487f4a36fec6ca4af21e25bf873f087e8e3fcf422f82af1a070801aad990caaab61858658e89924fdb28f78c1ece72fe

test:
  secret_key_base: ee2aaaa6fc9c640627aa7cd5c7567ce4f4f71bac2ab50a6a989e64052b9020918d8e37353e83d0dea79f6389e6a71ca3585d01076879b098b5019529c2e1a286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
